title:       "Thế-Anh Trần"
email:       "anhttmle@gmail.com"
description: >-
  AI Engineer Leader with 10+ years of experience in Machine Learning,
  Deep Learning, and Software Engineering. Passionate about the nature
  of intelligence.
author:      "Thế-Anh Trần"
baseurl:     ""
url:         ""

# Build settings
theme:   minima
plugins:
  - jekyll-feed

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .idea/
  - run_local.bat
